version: '3.8'
services:
  server:
    build: ./server
    image: shan4488/bits-food-server:v6
    environment:
      - PORT=8004
      - MONGODB_URL=${MONGODB_URL}
      - JWT=${JWT}
    ports:
      - "8004:8004"
    networks:
      - app-network

  client:
    build: ./client
    image: shan4488/bits-food-client:v6
    environment:
      - REACT_APP_API_HOST=http://localhost:8004/api/
    ports:
      - "3000:3000"
    depends_on:
      - server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
