version: '3.8'
services:
  server:
    build: ./server
    image: shan4488/bits-food-server:v1
    environment:
      - PORT=8080
      - MONGODB_URL=${MONGODB_URL}
      - JWT=${JWT}
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app
    networks:
      - app-network

  client:
    build: ./client
    image: shan4488/bits-food-client:v1
    environment:
      - REACT_APP_API_HOST=http://localhost:8080/api/
    ports:
      - "3000:3000"
    volumes:
      - ./client/src:/app/src
      - ./client/public:/app/public
    depends_on:
      - server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
