apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image:  shan4488/bits-food-client:v6
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: my-secret
